version: "3.7"
services:
  database:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 7014:3306
    environment:
      - MYSQL_ROOT_PASSWORD=blesta_root
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
  blesta:
    image: gusdecool/blesta
    build: ./
    volumes:
      - ./blesta:/app
    ports:
      - 7013:443
volumes:
  mysql_data:
    driver: local
